sudo: true
language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
#    - os: osx

sudo: required

before_install:
  - ./start-broker.sh

jobs:
  include:
    - stage: mqttv3 tests
      script: mvn --projects org.eclipse.paho.client.mqttv3,org.eclipse.paho.client.mqttv3.test test
    - stage: mqttv5 tests
      script: mvn --projects org.eclipse.paho.mqttv5.common,org.eclipse.paho.mqttv5.client test


addons:
  apt:
    sources:
      - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
      - mosquitto